//! The TypeScript side of the commands (PLAN.md H15), generated by a test
//! and checked by it, so a renamed command, argument or payload field fails
//! `npm run check` instead of failing at run time:
//!
//! - `app/src/lib/generated/ipc.ts`: the payloads' and events' types, from
//!   the Rust types by ts-rs (`declare_types`), as `settings::bindings` does
//!   for the settings;
//! - `app/src/lib/generated/commands.ts`: one typed wrapper per command
//!   `lib.rs`'s `generate_handler!` registers, read from each command's
//!   signature with syn: its name, its arguments in camelCase (Tauri's own
//!   ones, such as `AppHandle` and `State`, left out) and what it returns
//!   (`Result<T, _>` resolves to `T`; the error rejects the promise).
//!
//! `app/src/lib/api.ts` calls the wrappers. The test fails when either file
//! is out of date; `ANOMP_WRITE_BINDINGS=1 cargo test bindings` rewrites
//! them. A type a command uses must be declared here or in the settings'
//! bindings, or the test names it.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TypeVisitor, TS};

/// Names that aren't types of their own on the TypeScript side: Rust type
/// aliases, and what a raw channel carries.
const ALIASES: &[(&str, &str)] = &[("Uid", "number"), ("InvokeResponseBody", "ArrayBuffer")];

/// Arguments Tauri fills in itself; the frontend never passes them.
const INJECTED: &[&str] = &[
    "AppHandle",
    "State",
    "Window",
    "WebviewWindow",
    "Webview",
    "Request",
];

fn src_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("src")
}

/// The paths of the commands in `generate_handler![…]`, as written there
/// (`library::commands::library_browse`), comments and attributes left out.
fn handler_paths(lib_rs: &str) -> Vec<String> {
    let start = lib_rs
        .find("generate_handler![")
        .expect("lib.rs has no generate_handler!")
        + "generate_handler![".len();
    let mut paths = Vec::new();
    for line in lib_rs[start..].lines() {
        let line = line.split("//").next().unwrap_or_default().trim();
        if line.starts_with("#[") {
            continue;
        }
        if line.starts_with(']') {
            return paths;
        }
        paths.extend(
            line.split(',')
                .map(str::trim)
                .filter(|entry| !entry.is_empty())
                .map(str::to_owned),
        );
    }
    panic!("generate_handler! isn't closed");
}

/// The file holding module `path` (`["library", "commands"]`).
fn module_file(path: &[&str]) -> PathBuf {
    let src = src_dir();
    if path.is_empty() {
        return src.join("lib.rs");
    }
    let joined = path.join("/");
    let file = src.join(format!("{joined}.rs"));
    if file.exists() {
        file
    } else {
        src.join(joined).join("mod.rs")
    }
}

/// One command, as the frontend calls it.
#[derive(Debug, PartialEq)]
struct Command {
    name: String,
    /// (camelCase name, TypeScript type, optional).
    args: Vec<(String, String, bool)>,
    returns: String,
}

fn camel_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in name.trim_start_matches("r#").chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// The generic arguments of a path segment.
fn type_args(segment: &syn::PathSegment) -> Vec<&syn::Type> {
    match &segment.arguments {
        syn::PathArguments::AngleBracketed(args) => args
            .args
            .iter()
            .filter_map(|arg| match arg {
                syn::GenericArgument::Type(ty) => Some(ty),
                _ => None,
            })
            .collect(),
        _ => Vec::new(),
    }
}

/// Where a command's file gets its names from: its module and its `use`
/// items (each name to the path it stands for).
struct Scope {
    module: Vec<String>,
    uses: HashMap<String, String>,
}

impl Scope {
    fn of(module: &[&str], file: &syn::File) -> Scope {
        let module: Vec<String> = module.iter().map(|s| (*s).to_owned()).collect();
        let mut uses = HashMap::new();
        for item in &file.items {
            if let syn::Item::Use(item) = item {
                flatten_use(&item.tree, Vec::new(), &mut uses);
            }
        }
        // `self::`, `super::` and `crate::` made absolute.
        let uses = uses
            .into_iter()
            .map(|(name, path): (String, Vec<String>)| (name, absolute(&module, &path)))
            .collect();
        Scope { module, uses }
    }

    /// The full path (`crate::library::Folder`) a name in this file stands
    /// for: imported, else defined here.
    fn resolve(&self, name: &str) -> String {
        self.uses.get(name).cloned().unwrap_or_else(|| {
            let mut path = vec!["crate".to_owned()];
            path.extend(self.module.iter().cloned());
            path.push(name.to_owned());
            path.join("::")
        })
    }
}

fn flatten_use(tree: &syn::UseTree, prefix: Vec<String>, out: &mut HashMap<String, Vec<String>>) {
    match tree {
        syn::UseTree::Path(path) => {
            let mut prefix = prefix;
            prefix.push(path.ident.to_string());
            flatten_use(&path.tree, prefix, out);
        }
        syn::UseTree::Name(name) => {
            let ident = name.ident.to_string();
            let mut path = prefix.clone();
            if ident != "self" {
                path.push(ident.clone());
            }
            let key = if ident == "self" {
                prefix.last().cloned().unwrap_or_default()
            } else {
                ident
            };
            out.insert(key, path);
        }
        syn::UseTree::Rename(rename) => {
            let mut path = prefix;
            path.push(rename.ident.to_string());
            out.insert(rename.rename.to_string(), path);
        }
        syn::UseTree::Group(group) => {
            for tree in &group.items {
                flatten_use(tree, prefix.clone(), out);
            }
        }
        syn::UseTree::Glob(_) => {}
    }
}

fn absolute(module: &[String], path: &[String]) -> String {
    let mut base: Vec<String> = Vec::new();
    let mut rest = path;
    match path.first().map(String::as_str) {
        Some("crate") => {
            base.push("crate".into());
            rest = &path[1..];
        }
        Some("self") => {
            base.push("crate".into());
            base.extend(module.iter().cloned());
            rest = &path[1..];
        }
        Some("super") => {
            base.push("crate".into());
            let mut up = module.to_vec();
            while rest.first().map(String::as_str) == Some("super") {
                up.pop();
                rest = &rest[1..];
            }
            base.extend(up);
        }
        _ => {}
    }
    base.extend(rest.iter().cloned());
    base.join("::")
}

/// The TypeScript names of the declared types: by full Rust path, and by
/// Rust name for a path a re-export hides.
struct Names {
    by_path: HashMap<String, String>,
    by_ident: HashMap<String, Vec<String>>,
    settings: BTreeSet<String>,
}

impl Names {
    fn ts_name(&self, scope: &Scope, ident: &str) -> Result<String, String> {
        if let Some(ts) = self.by_path.get(&scope.resolve(ident)) {
            return Ok(ts.clone());
        }
        match self.by_ident.get(ident).map(Vec::as_slice) {
            Some([only]) => return Ok(only.clone()),
            Some(several) if several.len() > 1 => {
                return Err(format!("{ident} is ambiguous: {several:?}"))
            }
            _ => {}
        }
        if self.settings.contains(ident) {
            return Ok(ident.to_owned());
        }
        Err(format!(
            "{} has no TypeScript binding (derive ts_rs::TS on it and add it to declare_types)",
            scope.resolve(ident)
        ))
    }
}

/// A Rust type as TypeScript sees it once serde has serialized it. The
/// names of declared types it uses are recorded in `used`, to be imported.
fn ts_type(
    ty: &syn::Type,
    scope: &Scope,
    names: &Names,
    used: &mut BTreeSet<String>,
) -> Result<String, String> {
    let map = |t: &syn::Type, used: &mut BTreeSet<String>| ts_type(t, scope, names, used);
    match ty {
        syn::Type::Reference(reference) => map(&reference.elem, used),
        syn::Type::Paren(inner) => map(&inner.elem, used),
        syn::Type::Group(inner) => map(&inner.elem, used),
        syn::Type::Slice(slice) => Ok(format!("{}[]", wrap(map(&slice.elem, used)?))),
        syn::Type::Array(array) => Ok(format!("{}[]", wrap(map(&array.elem, used)?))),
        syn::Type::Tuple(tuple) if tuple.elems.is_empty() => Ok("void".into()),
        syn::Type::Tuple(tuple) => {
            let items: Result<Vec<_>, _> = tuple.elems.iter().map(|t| map(t, used)).collect();
            Ok(format!("[{}]", items?.join(", ")))
        }
        syn::Type::Path(path) => {
            let segment = path.path.segments.last().expect("a path has a segment");
            let name = segment.ident.to_string();
            let args = type_args(segment);
            let arg = |i: usize, used: &mut BTreeSet<String>| -> Result<String, String> {
                let ty = args
                    .get(i)
                    .ok_or_else(|| format!("{name} without its type argument"))?;
                map(ty, used)
            };
            if let Some((_, ts)) = ALIASES.iter().find(|(alias, _)| *alias == name) {
                return Ok((*ts).to_owned());
            }
            Ok(match name.as_str() {
                "String" | "str" | "PathBuf" | "Path" | "char" => "string".into(),
                "bool" => "boolean".into(),
                "i8" | "i16" | "i32" | "i64" | "isize" | "u8" | "u16" | "u32" | "u64" | "usize"
                | "f32" | "f64" => "number".into(),
                "Option" => format!("{} | null", arg(0, used)?),
                "Vec" | "VecDeque" | "BTreeSet" | "HashSet" => {
                    format!("{}[]", wrap(arg(0, used)?))
                }
                "HashMap" | "BTreeMap" => format!("Record<{}, {}>", arg(0, used)?, arg(1, used)?),
                "Box" | "Arc" | "Rc" | "Cow" | "Result" => arg(0, used)?,
                "Value" => "unknown".into(),
                "Channel" => format!("Channel<{}>", arg(0, used)?),
                _ => {
                    let ts = names.ts_name(scope, &name)?;
                    used.insert(ts.clone());
                    if args.is_empty() {
                        ts
                    } else {
                        let items: Result<Vec<_>, _> =
                            (0..args.len()).map(|i| arg(i, used)).collect();
                        format!("{ts}<{}>", items?.join(", "))
                    }
                }
            })
        }
        _ => Err("a type the generator doesn't map".into()),
    }
}

/// `T | null` inside an array needs brackets; a tuple doesn't.
fn wrap(ts: String) -> String {
    if ts.contains(" | ") && !ts.starts_with('[') {
        format!("({ts})")
    } else {
        ts
    }
}

fn is_command(function: &syn::ItemFn) -> bool {
    function.attrs.iter().any(|attr| {
        let path = attr.path();
        path.segments.last().is_some_and(|s| s.ident == "command")
            && path.segments.iter().any(|s| s.ident == "tauri")
    })
}

fn find_fn<'a>(items: &'a [syn::Item], name: &str) -> Option<&'a syn::ItemFn> {
    items.iter().find_map(|item| match item {
        syn::Item::Fn(function) if function.sig.ident == name && is_command(function) => {
            Some(function)
        }
        _ => None,
    })
}

fn command(
    function: &syn::ItemFn,
    scope: &Scope,
    names: &Names,
    used: &mut BTreeSet<String>,
) -> Result<Command, String> {
    let name = function.sig.ident.to_string();
    let mut args = Vec::new();
    for input in &function.sig.inputs {
        let syn::FnArg::Typed(typed) = input else {
            return Err(format!("{name}: takes self"));
        };
        if let syn::Type::Path(path) = &*typed.ty {
            let last = path.path.segments.last().map(|s| s.ident.to_string());
            if last.is_some_and(|l| INJECTED.contains(&l.as_str())) {
                continue;
            }
        }
        let syn::Pat::Ident(ident) = &*typed.pat else {
            return Err(format!("{name}: an argument that isn't a plain name"));
        };
        let optional = matches!(&*typed.ty, syn::Type::Path(p)
            if p.path.segments.last().is_some_and(|s| s.ident == "Option"));
        let ts = ts_type(&typed.ty, scope, names, used).map_err(|e| format!("{name}: {e}"))?;
        args.push((camel_case(&ident.ident.to_string()), ts, optional));
    }
    let returns = match &function.sig.output {
        syn::ReturnType::Default => "void".to_owned(),
        syn::ReturnType::Type(_, ty) => {
            ts_type(ty, scope, names, used).map_err(|e| format!("{name}: {e}"))?
        }
    };
    Ok(Command {
        name,
        args,
        returns,
    })
}

/// Every registered command, in `generate_handler!`'s order, and the
/// TypeScript names they use.
fn commands(names: &Names) -> Result<(Vec<Command>, BTreeSet<String>), String> {
    let lib_rs = std::fs::read_to_string(src_dir().join("lib.rs")).unwrap();
    let mut files: HashMap<PathBuf, syn::File> = HashMap::new();
    let mut found = Vec::new();
    let mut used = BTreeSet::new();
    for path in handler_paths(&lib_rs) {
        let parts: Vec<&str> = path.split("::").collect();
        let (name, module) = parts.split_last().unwrap();
        let file = module_file(module);
        if !files.contains_key(&file) {
            let source = std::fs::read_to_string(&file)
                .map_err(|e| format!("{path}: can't read {}: {e}", file.display()))?;
            let parsed =
                syn::parse_file(&source).map_err(|e| format!("{}: {e}", file.display()))?;
            files.insert(file.clone(), parsed);
        }
        let parsed = &files[&file];
        let function = find_fn(&parsed.items, name).ok_or_else(|| {
            format!(
                "{path}: no #[tauri::command] fn {name} in {}",
                file.display()
            )
        })?;
        let scope = Scope::of(module, parsed);
        found.push(command(function, &scope, names, &mut used)?);
    }
    Ok((found, used))
}

/// One type `ipc.ts` declares.
struct Declared {
    /// Its TypeScript name.
    ts: String,
    /// Its full Rust path, `crate::…`.
    path: String,
    declaration: String,
}

/// Collects a type and, recursively, every type it depends on, skipping
/// the settings' (declared in settings.ts) and those already seen.
struct Collect<'a> {
    cfg: &'a Config,
    settings: &'a BTreeSet<String>,
    /// Full paths, generics left off: every instance of a generic type
    /// has one declaration.
    seen: BTreeSet<String>,
    out: Vec<Declared>,
}

impl TypeVisitor for Collect<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if T::output_path().is_none() {
            return;
        }
        let path = std::any::type_name::<T>();
        let path = path.split('<').next().unwrap_or(path);
        let path = match path.split_once("::") {
            Some((_, rest)) => format!("crate::{rest}"),
            None => path.to_owned(),
        };
        let ts = T::ident(self.cfg);
        if self.settings.contains(&ts) || !self.seen.insert(path.clone()) {
            return;
        }
        let mut declaration = String::new();
        if let Some(docs) = T::docs() {
            declaration.push_str(&docs);
        }
        declaration.push_str("export ");
        declaration.push_str(&T::decl(self.cfg));
        self.out.push(Declared {
            ts,
            path,
            declaration,
        });
        T::visit_dependencies(self);
    }
}

/// The types `ipc.ts` declares: these, which commands and events send, and
/// every type they contain.
fn declare_types(cfg: &Config, settings: &BTreeSet<String>) -> Vec<Declared> {
    let mut collect = Collect {
        cfg,
        settings,
        seen: BTreeSet::new(),
        out: Vec::new(),
    };
    macro_rules! declare {
        ($($ty:ty),* $(,)?) => {
            $(collect.visit::<$ty>();)*
        };
    }
    declare!(
        crate::library::access::FolderState,
        crate::library::access::FolderStatus,
        crate::library::Folder,
        crate::library::TrackSummary,
        crate::library::browse::GroupKey,
        crate::library::browse::Group,
        crate::library::browse::BrowsePage,
        crate::library::browse::RuleSpec,
        crate::library::scanner::ScanReport,
        crate::library::scanner::ScanProgress,
        crate::library::search::SearchKind,
        crate::library::search::ArtistHit,
        crate::library::search::AlbumHit,
        crate::library::search::SearchResults,
        crate::library::artists::ArtistAlbum,
        crate::metadata::artists::SourcedArticle,
        crate::metadata::albums::LinkStatus,
        crate::metadata::artists::ArtistInfo,
        crate::library::artists::ArtistPage,
        crate::library::covers::CoverAlbum,
        crate::library::covers::CoverWall,
        crate::library::recovery::DbCheck,
        crate::anomp::FileInfo,
        crate::library::info::TrackDetails,
        crate::library::smart::SmartOrder,
        crate::library::smart::SmartRules,
        crate::library::playlists::Playlist,
        crate::library::playlists::PlaylistEntry,
        crate::library::playlists::PlaylistPage,
        crate::library::marks::MarkKind,
        crate::library::marks::Favourites,
        crate::collection::CollectionChanged,
        crate::collection::DataImport,
        crate::metadata::jobs::MetadataChanged,
        crate::metadata::musicbrainz::Release,
        crate::metadata::albums::AlbumLink,
        crate::library::albums::AlbumTrack,
        crate::library::albums::AlbumDetails,
        crate::metadata::commands::SourceCandidates<ts_rs::Dummy>,
        crate::metadata::albums::ReleaseCandidate,
        crate::library::art::CoverCandidate,
        crate::metadata::commands::CoverChoices,
        crate::metadata::artists::ArtistCandidate,
        crate::metadata::musicbrainz::ReleaseGroupEntry,
        crate::metadata::discography::Discography,
        crate::anomp::PlayerState,
        crate::audio::PlayerStatus,
        crate::queue::model::Repeat,
        crate::queue::model::SleepTimer,
        crate::queue::SleepRequest,
        crate::queue::model::Skipped,
        crate::queue::model::QueueState,
        crate::anomp::SignalPath,
        crate::audio::Practice,
        crate::library::analysis::AnalysisProgress,
        crate::library::analysis::TrackAnalysis,
        crate::library::discover::AlbumCard,
        crate::history::views::RecentEntry,
        crate::history::views::TopKind,
        crate::history::views::TopEntry,
        crate::history::views::TopPlayed,
        crate::history::views::Highlights,
        crate::history::listenbrainz::ListenBrainzStatus,
        crate::library::health::HealthTrack,
        crate::library::health::HealthReport,
        crate::library::lyrics::Lyrics,
        crate::library::prefs::TrackPrefs,
        crate::library::prefs::AlbumPrefs,
        crate::remote::RemoteStatus,
        crate::remote::RemoteDevice,
        crate::updates::UpdateCheck,
        crate::shell::DroppedPaths,
        crate::library::browse::Filter,
        crate::library::playlists::ImportReport,
        crate::features::Prefs,
        crate::metadata::jobs::Progress,
        crate::audio::SignalPathPayload,
        crate::anomp::EffectInfo,
        crate::effects::EffectsStatus,
    );
    collect.out
}

const HEADER: &str = "// Generated by `cargo test` (src-tauri/src/bindings.rs); don't edit.\n\
                      // After changing a command or a type it sends, run\n\
                      // `ANOMP_WRITE_BINDINGS=1 cargo test bindings` in src-tauri.\n";

/// Whether `text` uses `name` as a whole word.
fn mentions(text: &str, name: &str) -> bool {
    text.match_indices(name).any(|(at, _)| {
        let before = text[..at].chars().next_back();
        let after = text[at + name.len()..].chars().next();
        !before.is_some_and(|c| c.is_alphanumeric() || c == '_')
            && !after.is_some_and(|c| c.is_alphanumeric() || c == '_')
    })
}

fn generate_ipc(declared: &[Declared], settings: &BTreeSet<String>) -> String {
    let body: String = declared
        .iter()
        .map(|d| format!("{}\n\n", d.declaration))
        .collect();
    let imported: Vec<&str> = settings
        .iter()
        .filter(|name| mentions(&body, name))
        .map(String::as_str)
        .collect();
    let mut out = format!("{HEADER}\n");
    if !imported.is_empty() {
        let _ = writeln!(
            out,
            "import type {{ {} }} from \"./settings\";\n",
            imported.join(", ")
        );
    }
    out.push_str(&body);
    out.trim_end().to_owned() + "\n"
}

fn generate_commands(commands: &[Command], used: &BTreeSet<String>, names: &Names) -> String {
    let mut out = format!("{HEADER}\nimport {{ invoke }} from \"@tauri-apps/api/core\";\n");
    if commands
        .iter()
        .any(|c| c.args.iter().any(|a| a.1.contains("Channel<")))
    {
        out.push_str("import type { Channel } from \"@tauri-apps/api/core\";\n");
    }
    let ipc: Vec<&str> = used
        .iter()
        .filter(|n| !names.settings.contains(*n))
        .map(String::as_str)
        .collect();
    let settings: Vec<&str> = used
        .iter()
        .filter(|n| names.settings.contains(*n))
        .map(String::as_str)
        .collect();
    for (list, module) in [(ipc, "ipc"), (settings, "settings")] {
        if !list.is_empty() {
            let _ = writeln!(
                out,
                "import type {{ {} }} from \"./{module}\";",
                list.join(", ")
            );
        }
    }
    out.push_str(
        "\n/** Every command lib.rs registers, by its camelCase name. */\nexport const commands = {\n",
    );
    for command in commands {
        let returns = &command.returns;
        let name = &command.name;
        if command.args.is_empty() {
            let _ = writeln!(
                out,
                "  {}: () => invoke<{returns}>(\"{name}\"),",
                camel_case(name)
            );
        } else {
            let fields: Vec<String> = command
                .args
                .iter()
                .map(|(arg, ts, optional)| {
                    format!("{arg}{}: {ts}", if *optional { "?" } else { "" })
                })
                .collect();
            let _ = writeln!(
                out,
                "  {}: (args: {{ {} }}) => invoke<{returns}>(\"{name}\", args),",
                camel_case(name),
                fields.join("; ")
            );
        }
    }
    out.push_str("};\n");
    out
}

/// The type names `settings.ts` declares.
fn settings_names(settings_ts: &str) -> BTreeSet<String> {
    settings_ts
        .lines()
        .filter_map(|line| line.strip_prefix("export type "))
        .filter_map(|rest| rest.split([' ', '<', '=']).next())
        .map(str::to_owned)
        .collect()
}

/// Both files, as they should be.
fn generate() -> Vec<(&'static str, String)> {
    let generated = Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/generated");
    let cfg = Config::new().with_large_int("number");
    let settings = settings_names(&std::fs::read_to_string(generated.join("settings.ts")).unwrap());
    let mut declared = declare_types(&cfg, &settings);
    // By name: the order ts-rs visits dependencies in differs between
    // builds, and the file must not.
    declared.sort_by(|a, b| a.ts.cmp(&b.ts));
    let mut by_path = HashMap::new();
    let mut by_ident: HashMap<String, Vec<String>> = HashMap::new();
    for d in &declared {
        assert!(
            by_path.insert(d.path.clone(), d.ts.clone()).is_none(),
            "{} declared twice",
            d.path
        );
        let rust_name = d.path.rsplit("::").next().unwrap().to_owned();
        by_ident.entry(rust_name).or_default().push(d.ts.clone());
    }
    let mut ts_names: Vec<&str> = declared.iter().map(|d| d.ts.as_str()).collect();
    ts_names.sort_unstable();
    for pair in ts_names.windows(2) {
        assert_ne!(pair[0], pair[1], "two types are called {} in TypeScript: rename one with #[cfg_attr(test, ts(rename = \"…\"))]", pair[0]);
    }
    let names = Names {
        by_path,
        by_ident,
        settings,
    };
    let (commands, used) = commands(&names).unwrap_or_else(|e| panic!("{e}"));
    vec![
        ("ipc.ts", generate_ipc(&declared, &names.settings)),
        ("commands.ts", generate_commands(&commands, &used, &names)),
    ]
}

#[test]
fn bindings_are_up_to_date() {
    let generated = Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/generated");
    for (name, text) in generate() {
        let path = generated.join(name);
        if std::env::var_os("ANOMP_WRITE_BINDINGS").is_some() {
            std::fs::write(&path, &text).unwrap();
            continue;
        }
        let committed = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            committed == text,
            "{} is out of date: run `ANOMP_WRITE_BINDINGS=1 cargo test bindings` in src-tauri",
            path.display()
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(declared: &[(&str, &str)], settings: &[&str]) -> Names {
        let mut by_ident: HashMap<String, Vec<String>> = HashMap::new();
        for (path, ts) in declared {
            by_ident
                .entry(path.rsplit("::").next().unwrap().to_owned())
                .or_default()
                .push((*ts).to_owned());
        }
        Names {
            by_path: declared
                .iter()
                .map(|(path, ts)| ((*path).to_owned(), (*ts).to_owned()))
                .collect(),
            by_ident,
            settings: settings.iter().map(|s| (*s).to_owned()).collect(),
        }
    }

    fn scope(module: &[&str], source: &str) -> Scope {
        Scope::of(module, &syn::parse_file(source).unwrap())
    }

    fn command_of(source: &str, names: &Names) -> Result<(Command, BTreeSet<String>), String> {
        let file = syn::parse_file(source).unwrap();
        let scope = Scope::of(&["library", "commands"], &file);
        let syn::Item::Fn(function) = file
            .items
            .iter()
            .find(|i| matches!(i, syn::Item::Fn(_)))
            .unwrap()
        else {
            unreachable!()
        };
        let mut used = BTreeSet::new();
        command(function, &scope, names, &mut used).map(|c| (c, used))
    }

    #[test]
    fn handler_paths_skip_comments_and_attributes() {
        let lib_rs = "fn run() { tauri::generate_handler![\n    // The dev page's.\n    #[cfg(debug_assertions)]\n    dev::core_version,\n    library::commands::library_browse, queue::queue_get, // trailing\n]) }";
        assert_eq!(
            handler_paths(lib_rs),
            [
                "dev::core_version",
                "library::commands::library_browse",
                "queue::queue_get"
            ]
        );
    }

    #[test]
    fn arguments_are_camel_case() {
        assert_eq!(camel_case("folder_id"), "folderId");
        assert_eq!(camel_case("r#type"), "type");
        assert_eq!(camel_case("library_add_folder"), "libraryAddFolder");
    }

    #[test]
    fn a_command_maps_to_its_typescript_call() {
        let names = names(&[("crate::library::Folder", "Folder")], &["SortRule"]);
        let source = r#"
            use crate::library::Folder;
            #[tauri::command]
            pub async fn library_folders<R: Runtime>(
                app: AppHandle<R>,
                state: State<'_, LibraryState>,
                folder_id: i64,
                rules: Vec<SortRule>,
                name: Option<String>,
                pairs: Vec<(u32, Option<f64>)>,
                frames: tauri::ipc::Channel<InvokeResponseBody>,
                uid: Uid,
            ) -> Result<Vec<Folder>, String> { todo!() }
        "#;
        let (command, used) = command_of(source, &names).unwrap();
        assert_eq!(command.name, "library_folders");
        assert_eq!(
            command.args,
            [
                ("folderId".to_owned(), "number".to_owned(), false),
                ("rules".to_owned(), "SortRule[]".to_owned(), false),
                ("name".to_owned(), "string | null".to_owned(), true),
                (
                    "pairs".to_owned(),
                    "[number, number | null][]".to_owned(),
                    false
                ),
                (
                    "frames".to_owned(),
                    "Channel<ArrayBuffer>".to_owned(),
                    false
                ),
                ("uid".to_owned(), "number".to_owned(), false),
            ]
        );
        assert_eq!(command.returns, "Folder[]");
        assert_eq!(
            used,
            BTreeSet::from(["Folder".to_owned(), "SortRule".to_owned()])
        );
    }

    #[test]
    fn a_command_without_a_result_returns_void() {
        let source = "#[tauri::command]\npub fn player_play() {}";
        assert_eq!(
            command_of(source, &names(&[], &[])).unwrap().0.returns,
            "void"
        );
    }

    #[test]
    fn types_resolve_through_the_files_uses_to_their_typescript_names() {
        let names = names(
            &[
                ("crate::library::playlists::ImportReport", "PlaylistImport"),
                ("crate::library::transfer::ImportReport", "DataImportReport"),
                ("crate::library::commands::Local", "Local"),
            ],
            &[],
        );
        let uses = scope(
            &["library", "commands"],
            "use super::playlists::{self, ImportReport as Imported};\nuse crate::library::transfer::ImportReport;",
        );
        assert_eq!(names.ts_name(&uses, "Imported").unwrap(), "PlaylistImport");
        assert_eq!(
            names.ts_name(&uses, "ImportReport").unwrap(),
            "DataImportReport"
        );
        assert_eq!(names.ts_name(&uses, "Local").unwrap(), "Local");
        assert_eq!(uses.resolve("playlists"), "crate::library::playlists");
    }

    #[test]
    fn an_unknown_or_ambiguous_type_is_an_error() {
        let names = names(
            &[
                ("crate::a::Report", "AReport"),
                ("crate::b::Report", "BReport"),
            ],
            &[],
        );
        let nothing = scope(&["c"], "");
        assert!(names
            .ts_name(&nothing, "Report")
            .unwrap_err()
            .contains("ambiguous"));
        assert!(names
            .ts_name(&nothing, "Missing")
            .unwrap_err()
            .contains("crate::c::Missing"));
    }

    #[test]
    fn settings_names_and_mentions() {
        let ts = "export type AppSettings = { a: number };\nexport type SourceId = \"a\" | \"b\";\nexport type Gains<T> = T[];";
        assert_eq!(
            settings_names(ts),
            BTreeSet::from([
                "AppSettings".to_owned(),
                "SourceId".to_owned(),
                "Gains".to_owned()
            ])
        );
        assert!(mentions("source: SourceId, ", "SourceId"));
        assert!(!mentions("ids: SourceIds", "SourceId"));
    }
}
