//! The user guide's settings reference (PLAN.md Phase 7c, D1),
//! `docs/user-guide/settings-reference.md`: every setting the app keeps,
//! under its section of Settings, named as the UI names it (from
//! `en.json`) with its default (from the Rust defaults) and its range.
//!
//! Generated by a test and checked by it, like the TypeScript bindings:
//! the test fails while the committed file differs, and
//! `ANOMP_WRITE_BINDINGS=1 cargo test bindings` rewrites it. It also fails
//! when a setting has no row here (every value in the defaults must be
//! covered, or listed in `UNLISTED` with why) or a row names a setting or
//! a message that's gone, so a new setting can't be left out of the guide.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::anomp::EffectUnit;
use crate::library::rules::SortSettings;
use crate::metadata::settings::{ServiceSettings, SourceId};
use crate::settings::AppSettings;

/// The UI's messages, by key.
struct Labels(BTreeMap<String, Value>);

impl Labels {
    fn load() -> Labels {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/i18n/en.json");
        let text = std::fs::read_to_string(&path).expect("en.json is readable");
        Labels(serde_json::from_str(&text).expect("en.json is a JSON object"))
    }

    /// The message `key`, its plural's "other" form if it has one.
    fn get(&self, key: &str) -> String {
        match self.0.get(key) {
            Some(Value::String(text)) => text.clone(),
            Some(Value::Object(forms)) => forms["other"].as_str().unwrap_or_default().to_owned(),
            _ => panic!("en.json has no message {key}"),
        }
    }

    /// The message `key` with `{name}` placeholders filled in.
    fn fill(&self, key: &str, values: &[(&str, &str)]) -> String {
        values.iter().fold(self.get(key), |text, (name, value)| {
            text.replace(&format!("{{{name}}}"), value)
        })
    }
}

/// How a value is shown.
enum Shown {
    /// On or off.
    Switch,
    /// One of several, each a JSON string with its label's key.
    Choice(&'static [(&'static str, &'static str)]),
    /// A number with its unit ("dB", "s"…, or "" for none).
    Number(&'static str),
    /// Anything else, written by a function.
    Custom(fn(&Value, &Labels) -> String),
}

/// One row of the reference: a setting, or a group of them shown as one.
struct Row {
    /// Its section of Settings (the `settings.<id>` message).
    section: &'static str,
    /// Where it is in the settings' JSON; it covers everything under it.
    path: &'static str,
    /// The UI's name for it.
    label: &'static str,
    shown: Shown,
    /// The values it can take, when that isn't plain from the choices.
    range: &'static str,
}

const fn row(
    section: &'static str,
    path: &'static str,
    label: &'static str,
    shown: Shown,
    range: &'static str,
) -> Row {
    Row {
        section,
        path,
        label,
        shown,
        range,
    }
}

/// The sections, in the order Settings lists them, with what isn't one
/// (`AppSettings`, the sort rules, the online sources) last.
const SECTIONS: &[&str] = &[
    "settings.general",
    "settings.library",
    "settings.sorting",
    "settings.display",
    "settings.appearance",
    "settings.playback",
    "settings.equaliser",
    "settings.effects",
    "settings.recording",
    "settings.visualizer",
    "settings.sources",
    "settings.features",
    "settings.about",
];

/// Values in the defaults that aren't settings the user sees, and why.
const UNLISTED: &[(&str, &str)] = &[
    (
        "app.window.visualizerNoteSeen",
        "remembers that the visualizer's note was read",
    ),
    (
        "app.appearance.saved",
        "the user's own themes, none at first",
    ),
];

const COLUMNS: &[(&str, &str)] = &[
    ("trackNumber", "column.trackNumber"),
    ("artist", "column.artist"),
    ("album", "column.album"),
    ("albumArtist", "column.albumArtist"),
    ("year", "column.year"),
    ("genre", "column.genre"),
    ("duration", "column.duration"),
    ("format", "column.format"),
    ("bitrate", "column.bitrate"),
    ("sampleRate", "column.sampleRate"),
    ("playCount", "column.playCount"),
    ("lastPlayed", "column.lastPlayed"),
    ("dateAdded", "column.dateAdded"),
    ("composer", "column.composer"),
    ("rating", "column.rating"),
];

const FACTS: &[(&str, &str)] = &[
    ("date", "column.date"),
    ("label", "column.label"),
    ("country", "column.country"),
    ("format", "column.format"),
    ("type", "column.type"),
];

const REPLAY_GAIN: &[(&str, &str)] = &[
    ("off", "playback.rgOff"),
    ("track", "playback.rgTrack"),
    ("album", "playback.rgAlbum"),
];

const CROSSFEED: &[(&str, &str)] = &[
    ("off", "signal.off"),
    ("light", "signal.crossfeedLight"),
    ("medium", "signal.crossfeedMedium"),
    ("strong", "signal.crossfeedStrong"),
];

const RECORDING_FORMATS: &[(&str, &str)] = &[
    ("wav", "recording.format.wav"),
    ("aiff", "recording.format.aiff"),
    ("flac", "recording.format.flac"),
    ("alac", "recording.format.alac"),
    ("aac", "recording.format.aac"),
    ("mp3", "recording.format.mp3"),
];

const COVER_WALL: &[(&str, &str)] = &[
    ("year", "vizOptions.sameYear"),
    ("artist", "vizOptions.sameArtist"),
];

const SCHEMES: &[(&str, &str)] = &[
    ("system", "appearance.scheme.system"),
    ("light", "appearance.scheme.light"),
    ("dark", "appearance.scheme.dark"),
];

const FONTS: &[(&str, &str)] = &[
    ("system", "appearance.font.system"),
    ("rounded", "appearance.font.rounded"),
    ("serif", "appearance.font.serif"),
    ("mono", "appearance.font.mono"),
    ("humanist", "appearance.font.humanist"),
];

const DENSITIES: &[(&str, &str)] = &[
    ("compact", "appearance.density.compact"),
    ("regular", "appearance.density.regular"),
    ("roomy", "appearance.density.roomy"),
];

/// The visualizations, by id, in the picker's order
/// (`app/src/lib/visualizer/index.ts`).
const VISUALIZATIONS: &[&str] = &[
    "bars",
    "scope",
    "vu",
    "covers",
    "ridges",
    "fifths",
    "vectorscope",
    "kaleidoscope",
    "tonnetz",
    "recurrence",
    "cymatics",
    "portrait",
    "spiral",
    "harmonograph",
    "rhythm",
    "stage",
    "resonance",
    "harmony",
];

fn list(value: &Value, choices: &[(&str, &str)], labels: &Labels, empty: &str) -> String {
    let names: Vec<String> = value
        .as_array()
        .into_iter()
        .flatten()
        .map(|item| choice(item, choices, labels))
        .collect();
    if names.is_empty() {
        labels.get(empty)
    } else {
        names.join(", ")
    }
}

fn choice(value: &Value, choices: &[(&str, &str)], labels: &Labels) -> String {
    let id = value.as_str().unwrap_or_default();
    let (_, key) = choices
        .iter()
        .find(|(candidate, _)| *candidate == id)
        .unwrap_or_else(|| panic!("no label for the choice {id}"));
    labels.get(key)
}

fn number(value: &Value) -> String {
    let number = value.as_f64().unwrap_or_default();
    if number.fract() == 0.0 {
        format!("{number:.0}")
    } else {
        format!("{number}")
    }
}

fn signed_db(value: &Value) -> String {
    let db = value.as_f64().unwrap_or_default();
    if db > 0.0 {
        format!("+{} dB", number(value))
    } else {
        format!("{} dB", number(value))
    }
}

/// `AppSettings`' rows, under `app`.
const APP_ROWS: &[Row] = &[
    row(
        "settings.general",
        "app.window.menuBarControls",
        "general.menuBarControls",
        Shown::Switch,
        "",
    ),
    row(
        "settings.general",
        "app.window.miniPlayerOnTop",
        "general.onTop",
        Shown::Switch,
        "",
    ),
    row(
        "settings.general",
        "app.window.trackNotifications",
        "general.trackNotifications",
        Shown::Switch,
        "",
    ),
    row(
        "settings.library",
        "app.library.rescanAtLaunch",
        "folders.rescanAtLaunch",
        Shown::Switch,
        "",
    ),
    row(
        "settings.library",
        "app.library.watchFolders",
        "folders.watch",
        Shown::Switch,
        "",
    ),
    row(
        "settings.display",
        "app.display.trackColumns",
        "display.columns",
        Shown::Custom(|value, labels| list(value, COLUMNS, labels, "display.onlyTitle")),
        "any of the columns, in any order",
    ),
    row(
        "settings.display",
        "app.display.albumFacts",
        "display.albumFacts",
        Shown::Custom(|value, labels| list(value, FACTS, labels, "display.none")),
        "any of the facts, in any order",
    ),
    row(
        "settings.display",
        "app.display.showDescriptions",
        "display.descriptions",
        Shown::Switch,
        "",
    ),
    row(
        "settings.display",
        "app.display.sidebarNowPlaying",
        "display.sidebarNowPlaying",
        Shown::Switch,
        "",
    ),
    // The theme's name, built-in preset and colours: the theme itself.
    row(
        "settings.appearance",
        "app.appearance.theme",
        "appearance.themes",
        Shown::Custom(|_, labels| labels.get("theme.system")),
        "a built-in theme, or one you saved",
    ),
    row(
        "settings.appearance",
        "app.appearance.theme.scheme",
        "appearance.scheme",
        Shown::Choice(SCHEMES),
        "",
    ),
    row(
        "settings.appearance",
        "app.appearance.theme.font",
        "appearance.font",
        Shown::Choice(FONTS),
        "",
    ),
    row(
        "settings.appearance",
        "app.appearance.theme.textSize",
        "appearance.textSize",
        Shown::Number("px"),
        "12 to 22 px",
    ),
    row(
        "settings.appearance",
        "app.appearance.theme.density",
        "appearance.density",
        Shown::Choice(DENSITIES),
        "",
    ),
    row(
        "settings.appearance",
        "app.appearance.theme.radius",
        "appearance.radius",
        Shown::Number("px"),
        "0 to 16 px",
    ),
    row(
        "settings.appearance",
        "app.appearance.theme.accentFromCover",
        "appearance.accentFromCover",
        Shown::Switch,
        "",
    ),
    row(
        "settings.appearance",
        "app.appearance.followSystemContrast",
        "appearance.systemContrast",
        Shown::Switch,
        "",
    ),
    row(
        "settings.playback",
        "app.output.device",
        "playback.device",
        Shown::Custom(|value, labels| {
            value
                .as_str()
                .map_or_else(|| labels.get("playback.systemDefault"), str::to_owned)
        }),
        "any output device macOS lists",
    ),
    row(
        "settings.playback",
        "app.output.bufferSize",
        "playback.bufferSize",
        Shown::Custom(|value, labels| {
            if value.is_null() {
                labels.get("playback.deviceDefault")
            } else {
                labels.fill("playback.samples", &[("count", &number(value))])
            }
        }),
        "the sizes the device offers",
    ),
    row(
        "settings.playback",
        "app.playback.replayGain",
        "playback.replayGain",
        Shown::Choice(REPLAY_GAIN),
        "",
    ),
    row(
        "settings.playback",
        "app.playback.preamp",
        "eq.preamp",
        Shown::Custom(|value, _| signed_db(value)),
        "−15 to +15 dB",
    ),
    row(
        "settings.playback",
        "app.playback.untaggedGain",
        "playback.untagged",
        Shown::Custom(|value, _| signed_db(value)),
        "−15 to +15 dB",
    ),
    row(
        "settings.playback",
        "app.playback.preventClipping",
        "playback.preventClipping",
        Shown::Switch,
        "",
    ),
    row(
        "settings.playback",
        "app.playback.crossfade",
        "playback.crossfadeTitle",
        Shown::Custom(|value, labels| {
            if value.as_f64() == Some(0.0) {
                labels.get("playback.crossfadeOff")
            } else {
                format!("{} s", number(value))
            }
        }),
        "off, or up to 12 s",
    ),
    row(
        "settings.equaliser",
        "app.equaliser.enabled",
        "eq.enabled",
        Shown::Switch,
        "",
    ),
    row(
        "settings.equaliser",
        "app.equaliser.followOutput",
        "eq.follow",
        Shown::Switch,
        "",
    ),
    row(
        "settings.equaliser",
        "app.equaliser.speakers",
        "eq.speakers",
        Shown::Custom(profile),
        "a preset, or ten bands of −12 to +12 dB and a preamp",
    ),
    row(
        "settings.equaliser",
        "app.equaliser.headphones",
        "eq.headphones",
        Shown::Custom(profile),
        "as the speakers' profile",
    ),
    row(
        "settings.effects",
        "app.features.effects",
        "effects.enabled",
        Shown::Switch,
        "",
    ),
    row(
        "settings.recording",
        "app.recording.format",
        "recording.format",
        Shown::Choice(RECORDING_FORMATS),
        "",
    ),
    row(
        "settings.recording",
        "app.recording.bits",
        "recording.bits",
        Shown::Custom(|value, labels| {
            if value.as_u64() == Some(32) {
                labels.get("recording.bitsFloat")
            } else {
                labels.fill("recording.bitsInteger", &[("bits", &number(value))])
            }
        }),
        "16-bit, 24-bit or 32-bit float (WAV only); for WAV, AIFF, FLAC and Apple Lossless",
    ),
    row(
        "settings.recording",
        "app.recording.bitrateKbps",
        "recording.bitrate",
        Shown::Number("kbps"),
        "96 to 320 kbps; for AAC and MP3",
    ),
    row(
        "settings.recording",
        "app.recording.cueSheet",
        "recording.cueSheet",
        Shown::Switch,
        "",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.visualization",
        "vizOptions.visualization",
        Shown::Custom(|value, labels| {
            labels.get(&format!("viz.{}.name", value.as_str().unwrap_or_default()))
        }),
        "any of the visualizations",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.cycleSeconds",
        "vizOptions.cycle",
        Shown::Custom(|value, labels| {
            if value.as_u64() == Some(0) {
                labels.get("vizOptions.never")
            } else {
                labels.fill("vizOptions.everySeconds", &[("count", &number(value))])
            }
        }),
        "never, or every few seconds to every few minutes",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.coverBasis",
        "vizOptions.coverWallShows",
        Shown::Choice(COVER_WALL),
        "",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.frameRate",
        "vizOptions.frameRate",
        Shown::Custom(|value, labels| labels.fill("vizOptions.rate", &[("rate", &number(value))])),
        "30 or 60 a second",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.sensitivity",
        "vizOptions.sensitivity",
        Shown::Custom(|value, _| format!("{:.0}%", value.as_f64().unwrap_or_default() * 100.0)),
        "25% to 400%",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.colorsFromCover",
        "vizOptions.coverColours",
        Shown::Switch,
        "",
    ),
    row(
        "settings.visualizer",
        "app.visualizer.calm",
        "vizOptions.calm",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.loudnessAnalysis",
        "feature.loudnessAnalysis",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.waveformSeekBar",
        "feature.waveformSeekBar",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.segueShuffle",
        "feature.segueShuffle",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.skipSilence",
        "features.skipSilence",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.skipSilenceAfter",
        "features.skipAfter",
        Shown::Number("s"),
        "1 to 60 s",
    ),
    row(
        "settings.features",
        "app.features.signalPath",
        "feature.signalPath",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.matchSampleRate",
        "feature.matchSampleRate",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.crossfeed",
        "features.crossfeed",
        Shown::Choice(CROSSFEED),
        "",
    ),
    row(
        "settings.features",
        "app.features.crossfeedHeadphonesOnly",
        "features.headphonesOnly",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.practiceMode",
        "feature.practiceMode",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.healthReport",
        "feature.healthReport",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.cueSheets",
        "feature.cueSheets",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.classical",
        "feature.classical",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.playbackPreferences",
        "feature.playbackPreferences",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.lyrics",
        "feature.lyrics",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.listeningHistory",
        "feature.listeningHistory",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.listenbrainz",
        "features.listenBrainz",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.recentlyPlayed",
        "feature.recentlyPlayed",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.topPlayed",
        "feature.topPlayed",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.libraryRadio",
        "feature.libraryRadio",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.radioAfterQueue",
        "feature.radioAfterQueue",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.recentlyAdded",
        "feature.recentlyAdded",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.onThisDay",
        "feature.onThisDay",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.moreInGenre",
        "feature.moreInGenre",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.recommendations",
        "feature.recommendations",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.outsideRecommendations",
        "feature.outsideRecommendations",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.similarArtists",
        "feature.similarArtists",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.themes",
        "feature.themes",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.recording",
        "feature.recording",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.remoteControl",
        "features.remoteSwitch",
        Shown::Switch,
        "",
    ),
    row(
        "settings.features",
        "app.features.remotePort",
        "features.port",
        Shown::Number(""),
        "1024 to 65535",
    ),
    row(
        "settings.about",
        "app.features.updateCheck",
        "updates.automatic",
        Shown::Switch,
        "",
    ),
];

/// An equaliser profile: its preset's name, or the bands' gains.
fn profile(value: &Value, labels: &Labels) -> String {
    let preset = value["preset"].as_str().unwrap_or("custom");
    labels.get(&format!("eq.preset.{preset}"))
}

/// The sort rules' and online sources' rows, under `sort` and `services`.
const OTHER_ROWS: &[Row] = &[
    row(
        "settings.sorting",
        "sort.rules",
        "sort.views",
        Shown::Custom(|value, _| {
            value
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(|rule| rule["name"].as_str())
                .collect::<Vec<_>>()
                .join(", ")
        }),
        "views you add, change or remove",
    ),
    row(
        "settings.sorting",
        "sort.ignoredArticles",
        "sort.skippedLabel",
        Shown::Custom(|value, _| {
            value
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(" ")
        }),
        "any words, or none",
    ),
    row(
        "settings.sources",
        "services.online",
        "services.online",
        Shown::Switch,
        "",
    ),
    row(
        "settings.sources",
        "services.autoMatch",
        "services.autoMatch",
        Shown::Switch,
        "",
    ),
    row(
        "settings.sources",
        "services.sources",
        "services.sources",
        Shown::Custom(|value, _| {
            let on: Vec<&str> = value
                .as_array()
                .into_iter()
                .flatten()
                .filter(|source| source["enabled"] == Value::Bool(true))
                .filter_map(|source| SourceId::from_str(source["id"].as_str()?))
                .map(|id| id.info().name)
                .collect();
            format!("On: {}", on.join(", "))
        }),
        "each source on or off; Discogs needs a token",
    ),
    row(
        "settings.sources",
        "services.order.release",
        "services.release",
        Shown::Custom(order),
        "any order",
    ),
    row(
        "settings.sources",
        "services.order.albumArt",
        "services.albumArt",
        Shown::Custom(order),
        "any order",
    ),
    row(
        "settings.sources",
        "services.order.artistInfo",
        "services.artistInfo",
        Shown::Custom(order),
        "any order",
    ),
    row(
        "settings.sources",
        "services.order.albumInfo",
        "services.albumInfo",
        Shown::Custom(order),
        "any order",
    ),
];

/// The sources for one kind of data, in the order they're tried.
fn order(value: &Value, _: &Labels) -> String {
    value
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|id| SourceId::from_str(id.as_str()?))
        .map(|id| id.info().name)
        .collect::<Vec<_>>()
        .join(", then ")
}

/// Every setting's default, as one JSON value: `app` (`AppSettings`),
/// `sort` and `services`.
fn defaults() -> Value {
    serde_json::json!({
        "app": AppSettings::default(),
        "sort": SortSettings::default(),
        "services": ServiceSettings::default(),
    })
}

/// Every value's path in `value` (an array is one value).
fn leaves(value: &Value, path: String, out: &mut Vec<String>) {
    match value {
        Value::Object(fields) if !fields.is_empty() => {
            for (name, field) in fields {
                leaves(field, format!("{path}.{name}"), out);
            }
        }
        _ => out.push(path),
    }
}

fn at<'a>(value: &'a Value, path: &str) -> Option<&'a Value> {
    path.split('.')
        .try_fold(value, |value, name| value.as_object()?.get(name))
}

fn covers(row: &str, leaf: &str) -> bool {
    leaf == row || leaf.starts_with(&format!("{row}."))
}

fn effect_rows(defaults: &Value, labels: &Labels) -> Vec<(String, String, String)> {
    let mut rows = Vec::new();
    let mut catalog = crate::effects::catalog().to_vec();
    catalog.sort_by_key(|info| info.position);
    for info in catalog {
        let effect = &defaults["app"]["effects"][&info.id];
        let name = labels.get(&format!("effects.{}", info.id));
        let state = if effect["enabled"] == Value::Bool(true) {
            "On"
        } else {
            "Off"
        };
        rows.push((
            name.clone(),
            format!(
                "{state}, {} {}",
                labels.get("effects.mix"),
                percent(info.default_mix)
            ),
            "on or off; mix 0% to 100%".to_owned(),
        ));
        for param in &info.params {
            let shown = |value: f64| effect_value(value, param.unit, labels);
            rows.push((
                format!(
                    "{name} › {}",
                    labels.get(&format!("effects.param.{}", param.id))
                ),
                shown(
                    effect["params"][&param.id]
                        .as_f64()
                        .unwrap_or(param.default_value),
                ),
                format!("{} to {}", shown(param.min), shown(param.max)),
            ));
        }
    }
    rows
}

fn percent(ratio: f64) -> String {
    format!("{:.0}%", ratio * 100.0)
}

/// A parameter's value as the Effects section shows it.
fn effect_value(value: f64, unit: EffectUnit, labels: &Labels) -> String {
    let short = |number: f64| {
        let rounded = (number * 100.0).round() / 100.0;
        if rounded.fract() == 0.0 {
            format!("{rounded:.0}")
        } else {
            format!("{rounded}")
        }
    };
    let (key, number) = match unit {
        EffectUnit::Ratio => return percent(value).replace('-', "−"),
        EffectUnit::Hertz if value >= 1000.0 => (
            "effects.unit.kilohertz",
            short((value / 100.0).round() / 10.0),
        ),
        EffectUnit::Hertz => ("effects.unit.hertz", short(value)),
        EffectUnit::Milliseconds => ("effects.unit.milliseconds", short(value)),
        EffectUnit::Seconds => ("effects.unit.seconds", short(value)),
        EffectUnit::Bits => ("effects.unit.bits", short(value)),
    };
    labels.fill(key, &[("value", &number)])
}

fn shown(row: &Row, value: &Value, labels: &Labels) -> String {
    match &row.shown {
        Shown::Switch => match value {
            Value::Bool(true) => "On".to_owned(),
            Value::Bool(false) => "Off".to_owned(),
            _ => panic!("{} isn't a switch", row.path),
        },
        Shown::Choice(choices) => choice(value, choices, labels),
        Shown::Number("") => number(value),
        Shown::Number(unit) => format!("{} {unit}", number(value)),
        Shown::Custom(write) => write(value, labels),
    }
}

/// The range column for a row: its own, or its choices'.
fn range(row: &Row, labels: &Labels) -> String {
    match &row.shown {
        Shown::Switch => "On or off".to_owned(),
        Shown::Choice(choices) => choices
            .iter()
            .map(|(_, key)| labels.get(key))
            .collect::<Vec<_>>()
            .join(", "),
        _ => row.range.to_owned(),
    }
}

/// A table cell: no line breaks or bars.
fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

fn generate() -> String {
    let labels = Labels::load();
    let defaults = defaults();
    let rows: Vec<&Row> = APP_ROWS.iter().chain(OTHER_ROWS).collect();

    // Every row names a setting, and every setting has a row.
    for row in &rows {
        assert!(
            at(&defaults, row.path).is_some(),
            "the reference's row {} names no setting",
            row.path
        );
        assert!(
            SECTIONS.contains(&row.section),
            "{}: no section {}",
            row.path,
            row.section
        );
        assert!(!range(row, &labels).is_empty(), "{}: no range", row.path);
    }
    let mut all = Vec::new();
    leaves(&defaults, String::new(), &mut all);
    for leaf in all.iter().map(|leaf| &leaf[1..]) {
        let listed = rows.iter().any(|row| covers(row.path, leaf))
            || leaf.starts_with("app.effects.")
            || UNLISTED.iter().any(|(path, _)| covers(path, leaf));
        assert!(
            listed,
            "the setting {leaf} isn't in the user guide's settings reference: add a row to guide.rs"
        );
    }
    for id in VISUALIZATIONS {
        labels.get(&format!("viz.{id}.name"));
    }

    let mut out = String::from(
        "<!-- Generated by `cargo test` from the app's settings (app/src-tauri/src/guide.rs);\n     \
         don't edit. After changing a setting or its label, run\n     \
         `ANOMP_WRITE_BINDINGS=1 cargo test bindings` in app/src-tauri. -->\n\n\
         # Settings reference\n\n\
         Every setting ano-mp keeps, under the section of Settings it is in, with the\n\
         value it has until you change it. [Chapter 11](11-settings.md) explains what\n\
         each one does. To open Settings, choose **ano-mp › Settings…** (⌘,).\n\n\
         Each section's **Reset to defaults** button (or **Reset**) puts that\n\
         section's settings back to the values below.\n",
    );
    for section in SECTIONS {
        let _ = write!(out, "\n## {}\n\n", labels.get(section));
        out.push_str("| Setting | Starts as | Can be |\n|---|---|---|\n");
        if *section == "settings.effects" {
            for row in rows.iter().filter(|row| row.section == *section) {
                let value = at(&defaults, row.path).unwrap();
                let _ = writeln!(
                    out,
                    "| {} | {} | {} |",
                    cell(&labels.get(row.label)),
                    cell(&shown(row, value, &labels)),
                    cell(&range(row, &labels))
                );
            }
            for (name, value, range) in effect_rows(&defaults, &labels) {
                let _ = writeln!(
                    out,
                    "| {} | {} | {} |",
                    cell(&name),
                    cell(&value),
                    cell(&range)
                );
            }
            continue;
        }
        for row in rows.iter().filter(|row| row.section == *section) {
            let value = at(&defaults, row.path).unwrap();
            let _ = writeln!(
                out,
                "| {} | {} | {} |",
                cell(&labels.get(row.label)),
                cell(&shown(row, value, &labels)),
                cell(&range(row, &labels))
            );
        }
    }
    out.push_str(
        "\nThe online sources' keys (a Discogs token, a ListenBrainz token) aren't settings:\n\
         they are kept in the macOS keychain, and none is saved at first. The folders in your\n\
         library and the recordings' folder are kept apart from the settings too.\n",
    );
    out
}

fn reference_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/user-guide/settings-reference.md")
}

#[test]
fn bindings_user_guide_settings_reference_is_up_to_date() {
    let path = reference_path();
    let generated = generate();
    if std::env::var_os("ANOMP_WRITE_BINDINGS").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &generated).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        committed == generated,
        "{} is out of date: run `ANOMP_WRITE_BINDINGS=1 cargo test bindings` in src-tauri",
        path.display()
    );
}
