#!/usr/bin/env python3
"""Keeps the dictionary of classes and types (docs/class-dictionary/,
PLAN.md Phase 7c D3) in step with the sources.

The types it expects, by layer (each a page of the dictionary):

- c-api.md, `core/include/anomp/anomp.h`: each `typedef struct` (opaque
  ones too), each callback `typedef`, and each unnamed `enum`, named by its
  constants' prefix (`ANOMP_STATE_*`);
- core.md, `core/src/`, and effects.md, `effects/src/` and
  `effects/include/`: each named C++ `class`, `struct`, `union` and `enum`
  with a body, nested ones qualified (`PlayerEngine::TrackOptions`);
- rust.md, `app/src-tauri/src/`: each `struct`, `enum` and `trait`, public
  or not, except test-only code: `#[cfg(test)]` items, and the files of
  modules declared under it (`bindings.rs`, `library/bench.rs`…);
- frontend.md, `app/src/`: each exported `type`, `interface`, `class` and
  `enum` of a `.ts` file, each state module (`state/player.svelte.ts`),
  each Svelte component (by name: `NowPlaying`; a route by its path:
  `routes/help/+page.svelte`), and each generated file once
  (`generated/ipc.ts`).

An entry is a `###` heading naming the type in backquotes, then a line
giving its kind and its file or files as links into the repo (a platform
unit's files, or a C API type's header and definition, share an entry),
then what it is. An entry whose kind starts with "Helper" (a small private
type) may stop at that line; every other entry needs a description.
Within a page the entries are in alphabetical order, ignoring case.

The index (README.md, between its `index` markers) is generated from the
pages: every name by folder, then A to Z, each linked to its entry.

Without --check, rewrites the index. With --check, changes nothing, lists
every problem (a type without an entry, an entry for a type that's gone, a
missing description, the order, a stale index) and exits non-zero if there
are any.

Usage: scripts/class-dictionary.py [--check]
"""

import argparse
import collections
import dataclasses
import itertools
import pathlib
import posixpath
import re
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DICTIONARY = REPO_ROOT / "docs" / "class-dictionary"
INDEX = "README.md"
INDEX_START = "<!-- index:start (generated by scripts/class-dictionary.py) -->"
INDEX_END = "<!-- index:end -->"

C_API = "core/include/anomp/anomp.h"
# Each page and the trees whose types it holds.
PAGES = {
    "c-api.md": ("C API", (C_API,)),
    "core.md": ("Core (C++)", ("core/src/",)),
    "effects.md": ("Effects (C++)", ("effects/src/", "effects/include/")),
    "rust.md": ("Rust backend", ("app/src-tauri/src/",)),
    "frontend.md": ("Frontend", ("app/src/",)),
}
CPP_EXTENSIONS = (".h", ".cpp", ".mm")
FRONTEND_ROOT = "app/src/"
GENERATED = "app/src/lib/generated/"
HELPER = "Helper"


@dataclasses.dataclass(frozen=True)
class Found:
    """A type in the sources: its name and the file declaring it."""

    name: str
    path: str


def tracked_files(root=REPO_ROOT):
    """Every file git tracks or would (not ignored), '/'-separated."""
    output = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return sorted(path for path in output.split("\0") if path)


# --- Reading the sources ----------------------------------------------------


RAW_STRING = re.compile(r'b?r(#*)"')
CHAR_LITERAL = re.compile(r"'(\\.[^']*|[^'\\\n])'")


def blank_out(text, raw_strings=False):
    """The text with comments, strings and character literals replaced by
    spaces (newlines kept), so braces and keywords in them don't count."""
    out = []
    i = 0
    n = len(text)

    def blank(end):
        out.append(re.sub(r"[^\n]", " ", text[i:end]))
        return end

    while i < n:
        c = text[i]
        two = text[i : i + 2]
        raw = None
        if (
            raw_strings
            and c in "br"
            and (i == 0 or not (text[i - 1].isalnum() or text[i - 1] == "_"))
        ):
            raw = RAW_STRING.match(text, i)
        if two == "//":
            end = text.find("\n", i)
            i = blank(n if end < 0 else end)
        elif two == "/*":
            end = text.find("*/", i + 2)
            i = blank(n if end < 0 else end + 2)
        elif raw:
            close = '"' + raw.group(1)
            end = text.find(close, raw.end())
            i = blank(n if end < 0 else end + len(close))
        elif c == '"':
            j = i + 1
            while j < n and text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            i = blank(j + 1)
        elif c == "'" and (literal := CHAR_LITERAL.match(text, i)):
            # A character literal ('{', '\n'), not a Rust lifetime ('a).
            i = blank(literal.end())
        else:
            out.append(c)
            i += 1
    return "".join(out)


CPP_DECLARATION = re.compile(
    r"(?:(?<=[;{}>:])|^)\s*(?:typedef\s+)?(?:(enum)(?:\s+(?:class|struct))?|class|struct|union)"
    r"\s+(?:\[\[[^\]]*\]\]\s*)?([A-Za-z_][\w:]*)"
    r"(?:\s+final)?\s*(?=[:{])",
    re.MULTILINE,
)
CPP_SCOPE = re.compile(r"(?:(?<=[;{}>:])|^)\s*namespace\b[^{;]*\{", re.MULTILINE)


def cpp_types(text):
    """The qualified names of the types a C++ file defines."""
    code = blank_out(text)
    # Where each type's (or namespace's) body opens: offset -> name, None
    # for a namespace, whose name doesn't qualify.
    opens = {}
    for match in CPP_DECLARATION.finditer(code):
        end = match.end()
        if code[end] == ":":
            if code[end : end + 2] == "::":
                continue
            # A base list or an enum's underlying type, up to the body.
            brace = code.find("{", end)
            semicolon = code.find(";", end)
            if brace < 0 or 0 <= semicolon < brace:
                continue
            end = brace
        opens[end] = match.group(2)
    for match in CPP_SCOPE.finditer(code):
        opens[match.end() - 1] = None
    names = []
    stack = []
    for i, c in enumerate(code):
        if c == "{":
            if i in opens and opens[i] is not None:
                name = opens[i]
                outer = [scope for scope in stack if scope]
                qualified = "::".join([*outer, name]) if "::" not in name else name
                names.append(qualified)
                stack.append(qualified.split("::")[-1] if "::" not in name else name)
            else:
                stack.append(None)
        elif c == "}" and stack:
            stack.pop()
    return names


C_TYPEDEF_STRUCT = re.compile(r"^typedef\s+struct\s+(\w+)", re.MULTILINE)
C_CALLBACK = re.compile(r"^typedef\s+[^;(]*\(\s*\*\s*(\w+)\s*\)", re.MULTILINE)
C_ENUM = re.compile(r"^enum\s*\{([^}]*)\}", re.MULTILINE)


def enum_prefix(constants):
    """`ANOMP_STATE_*` for ANOMP_STATE_EMPTY, ANOMP_STATE_STOPPED…"""
    common = constants[0]
    for constant in constants[1:]:
        while not constant.startswith(common):
            common = common[:-1]
    return common[: common.rfind("_") + 1] + "*"


def c_api_types(text):
    code = blank_out(text)
    names = C_TYPEDEF_STRUCT.findall(code) + C_CALLBACK.findall(code)
    for body in C_ENUM.findall(code):
        constants = re.findall(r"\b(ANOMP_\w+)", body)
        if constants:
            names.append(enum_prefix(constants))
    return names


RUST_ITEM = re.compile(
    r"^[ \t]*(?:pub(?:\([^)]*\))?\s+)?(?:unsafe\s+)?(struct|enum|trait|union)\s+([A-Za-z_]\w*)",
    re.MULTILINE,
)
# `#[cfg(test)]` before an item (other attributes and doc comments may
# come between), not before an enum variant or a match arm.
RUST_TEST_ATTRIBUTE = re.compile(
    r"#\[cfg\(test\)\](?=(?:\s*#\[[^\]]*\])*\s*(?:pub(?:\([^)]*\))?\s+)?"
    r"(?:unsafe\s+)?(?:async\s+)?(?:mod|struct|enum|trait|union|fn|impl|use|const|static|type)\b)"
)
RUST_TEST_MODULE = re.compile(r"#\[cfg\(test\)\]\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+(\w+)\s*;")


def rust_test_modules(path, text):
    """The files of the modules `path` declares under #[cfg(test)]: their
    paths, and their folders' (ending in '/')."""
    folder = posixpath.dirname(path)
    stem = posixpath.basename(path)[: -len(".rs")]
    if stem not in ("mod", "lib", "main"):
        folder = posixpath.join(folder, stem)
    found = set()
    for name in RUST_TEST_MODULE.findall(blank_out(text, raw_strings=True)):
        found |= {f"{folder}/{name}.rs", f"{folder}/{name}/"}
    return found


def skip_item(code, start):
    """The offset just past the item starting at `start`: its matching
    closing brace, or its semicolon if it has no body."""
    depth = 0
    i = start
    while i < len(code):
        c = code[i]
        if c == ";" and depth == 0:
            return i + 1
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return len(code)


def rust_types(text):
    """The structs, enums and traits of a Rust file, outside test-only code."""
    code = blank_out(text, raw_strings=True)
    # Blank every #[cfg(test)] item (a test module, a test-only type).
    for match in reversed(list(RUST_TEST_ATTRIBUTE.finditer(code))):
        end = skip_item(code, match.end())
        code = code[: match.start()] + re.sub(r"[^\n]", " ", code[match.start() : end]) + code[end:]
    return [match.group(2) for match in RUST_ITEM.finditer(code)]


TS_EXPORT = re.compile(
    r"^export\s+(?:declare\s+)?(?:abstract\s+)?(?:type|interface|class|enum)\s+([A-Za-z_]\w*)",
    re.MULTILINE,
)


def frontend_name(path):
    """A frontend file's own entry name, or None if it has none."""
    inner = path[len(FRONTEND_ROOT) :]
    if path.startswith(GENERATED):
        return "generated/" + inner[len("lib/generated/") :]
    if inner.startswith("routes/") and inner.endswith(".svelte"):
        return inner
    if inner.endswith(".svelte"):
        return posixpath.basename(inner)[: -len(".svelte")]
    if inner.startswith("lib/state/") and inner.endswith(".svelte.ts"):
        return "state/" + posixpath.basename(inner)
    return None


def page_of(path):
    for page, (_, roots) in PAGES.items():
        if any(path == root or path.startswith(root) for root in roots):
            return page
    return None


def expected(files, read):
    """{page: {Found}} for the repo's files, reading each with `read(path)`."""
    found = {page: set() for page in PAGES}
    test_only = set()
    for path in files:
        if page_of(path) == "rust.md" and path.endswith(".rs"):
            test_only |= rust_test_modules(path, read(path))
    for path in files:
        page = page_of(path)
        if (
            page is None
            or path in test_only
            or any(path.startswith(folder) for folder in test_only if folder.endswith("/"))
        ):
            continue
        names = []
        if page == "c-api.md":
            names = c_api_types(read(path))
        elif page in ("core.md", "effects.md"):
            if path.endswith(CPP_EXTENSIONS):
                names = cpp_types(read(path))
        elif page == "rust.md":
            if path.endswith(".rs"):
                names = rust_types(read(path))
        else:
            own = frontend_name(path)
            if own:
                names.append(own)
            if path.endswith(".ts") and not path.startswith(GENERATED):
                names += TS_EXPORT.findall(blank_out(read(path)))
        found[page] |= {Found(name, path) for name in names}
    # A C API struct the core defines (`struct anomp_engine`) is the
    # header's type: it belongs on the C API page, with both files.
    c_names = {item.name for item in found["c-api.md"]}
    for item in list(found["core.md"]):
        if item.name in c_names:
            found["core.md"].discard(item)
            found["c-api.md"].add(item)
    return found


# --- Reading the dictionary -------------------------------------------------


@dataclasses.dataclass
class Entry:
    name: str
    kind: str
    paths: list
    described: bool
    anchor: str = ""
    # (page, anchor) of each link into the developer guide.
    guide_links: list = dataclasses.field(default_factory=list)


GUIDE_PREFIX = "../developer-guide/"
HEADING = re.compile(r"^### `([^`]+)`\s*$")
LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")


def slug(heading):
    """GitHub's anchor for a heading (before numbering repeats)."""
    text = heading.strip().lower()
    text = re.sub(r"[^\w\- ]", "", text)
    return text.replace(" ", "-")


def anchors(text):
    """Each heading's GitHub anchor, by line number."""
    found = {}
    seen = collections.Counter()
    for i, line in enumerate(text.split("\n")):
        if re.match(r"^#{1,6} ", line):
            base = slug(line.lstrip("#"))
            found[i] = base if seen[base] == 0 else f"{base}-{seen[base]}"
            seen[base] += 1
    return found


def entries_of(text, page_dir="docs/class-dictionary"):
    """The entries of a page, in order, with GitHub's anchors."""
    entries = []
    heading_anchors = anchors(text)
    lines = text.split("\n")
    for i, line in enumerate(lines):
        anchor = heading_anchors.get(i, "")
        match = HEADING.match(line)
        if not match:
            continue
        rest = []
        for following in lines[i + 1 :]:
            if following.startswith("#"):
                break
            rest.append(following)
        paragraphs = [p.strip() for p in "\n".join(rest).split("\n\n") if p.strip()]
        meta = paragraphs[0] if paragraphs else ""
        kind = meta.split("·")[0].strip()
        paths = []
        guide_links = []
        for target in LINK.findall(meta):
            target, _, fragment = target.partition("#")
            if not target or re.match(r"^[a-z]+:", target):
                continue
            if target.startswith(GUIDE_PREFIX):
                guide_links.append((target[len(GUIDE_PREFIX) :], fragment))
                continue
            paths.append(posixpath.normpath(posixpath.join(page_dir, target)))
        entries.append(Entry(match.group(1), kind, paths, len(paragraphs) > 1, anchor, guide_links))
    return entries


def sort_key(name):
    return (name.lower().lstrip("_"), name)


def page_problems(page, entries, want):
    problems = []
    have = {Found(entry.name, path) for entry in entries for path in entry.paths}
    for item in sorted(want - have, key=lambda item: (sort_key(item.name), item.path)):
        problems.append(f"{page} has no entry for `{item.name}` ({item.path})")
    for item in sorted(have - want, key=lambda item: (sort_key(item.name), item.path)):
        problems.append(f"{page}'s entry `{item.name}` names {item.path}, which doesn't declare it")
    for entry in entries:
        if not entry.paths:
            problems.append(f"{page}'s entry `{entry.name}` links no file")
        if not entry.kind:
            problems.append(f"{page}'s entry `{entry.name}` gives no kind")
        elif not entry.described and not entry.kind.startswith(HELPER):
            problems.append(f"{page}'s entry `{entry.name}` has no description")
    names = [entry.name for entry in entries]
    for before, after in itertools.pairwise(names):
        if sort_key(after) < sort_key(before):
            problems.append(f"{page}: `{after}` comes before `{before}` alphabetically")
    return problems


# --- The index --------------------------------------------------------------


def folder_of(path):
    return posixpath.dirname(path) + "/"


def build_index(pages):
    """The generated index: by layer and folder, then A to Z."""
    lines = [INDEX_START, "", "## By layer and folder", ""]
    for page, (title, _) in PAGES.items():
        entries = pages.get(page, [])
        lines += [f"### {title}", ""]
        folders = collections.defaultdict(list)
        for entry in entries:
            for folder in sorted({folder_of(path) for path in entry.paths}):
                folders[folder].append(entry)
        for folder in sorted(folders):
            named = collections.Counter(entry.name for entry in folders[folder])
            links = []
            for entry in folders[folder]:
                link = f"[`{entry.name}`]({page}#{entry.anchor})"
                if named[entry.name] > 1:
                    files = [posixpath.basename(p) for p in entry.paths if folder_of(p) == folder]
                    link += f" ({', '.join(files)})"
                links.append(link)
            lines.append(f"- `{folder}`: {', '.join(links)}")
        lines.append("")
    lines += ["## A to Z", ""]
    everything = [(entry, page) for page, entries in pages.items() for entry in entries]
    by_letter = collections.defaultdict(list)
    for entry, page in everything:
        first = entry.name.lstrip("_")[:1].upper()
        by_letter[first if first.isalpha() else "#"].append((entry, page))
    for letter in sorted(by_letter):
        items = sorted(by_letter[letter], key=lambda pair: (sort_key(pair[0].name), pair[1]))
        lines += [f"### {letter}", ""]
        for entry, page in items:
            where = ", ".join(f"`{path}`" for path in entry.paths[:1])
            lines.append(f"- [`{entry.name}`]({page}#{entry.anchor}): {PAGES[page][0]}, {where}")
        lines.append("")
    lines.append(INDEX_END)
    return "\n".join(lines)


def with_index(index_text, pages):
    start = index_text.find(INDEX_START)
    end = index_text.find(INDEX_END)
    if start < 0 or end < 0:
        return None
    return index_text[:start] + build_index(pages) + index_text[end + len(INDEX_END) :]


def guide_problems(page, entries, read_file):
    """Links into the developer guide whose page or heading doesn't exist."""
    problems = []
    found = {}
    for entry in entries:
        for guide_page, fragment in entry.guide_links:
            if guide_page not in found:
                try:
                    text = read_file(f"docs/developer-guide/{guide_page}")
                except OSError:
                    text = None
                found[guide_page] = None if text is None else set(anchors(text).values())
            if found[guide_page] is None:
                problems.append(
                    f"{page}'s entry `{entry.name}` links {guide_page}, which is missing"
                )
            elif fragment and fragment not in found[guide_page]:
                problems.append(
                    f"{page}'s entry `{entry.name}` links {guide_page}#{fragment}, "
                    "which isn't a heading there"
                )
    return problems


def problems_in(read_page, files, read_file):
    """Every problem, and the index as it should be (None if unmarked)."""
    want = expected(files, read_file)
    problems = []
    pages = {}
    for page in PAGES:
        text = read_page(page)
        if text is None:
            problems.append(f"docs/class-dictionary/{page} is missing")
            continue
        pages[page] = entries_of(text)
        problems += page_problems(page, pages[page], want[page])
        problems += guide_problems(page, pages[page], read_file)
    index_text = read_page(INDEX)
    new_index = None if index_text is None else with_index(index_text, pages)
    if new_index is None:
        problems.append(f"docs/class-dictionary/{INDEX} is missing or has no index markers")
    return problems, index_text, new_index


def main():
    parser = argparse.ArgumentParser(description="Check the class dictionary; write its index.")
    parser.add_argument("--check", action="store_true", help="change nothing; fail on a problem")
    args = parser.parse_args()

    def read_page(name):
        path = DICTIONARY / name
        return path.read_text("utf-8") if path.exists() else None

    files = tracked_files()
    problems, index_text, new_index = problems_in(
        read_page, files, lambda path: (REPO_ROOT / path).read_text("utf-8")
    )
    if new_index is not None and new_index != index_text:
        if args.check:
            problems.append(f"{INDEX}'s index is stale: run scripts/class-dictionary.py")
        else:
            (DICTIONARY / INDEX).write_text(new_index, "utf-8")
            print(f"class-dictionary: wrote {INDEX}'s index")
    for problem in problems:
        print(f"class-dictionary: {problem}")
    if not problems:
        total = sum(len(entries_of(read_page(page))) for page in PAGES)
        print(f"class-dictionary: {total} entries cover every type in the tree")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
